# This is a config for E2B sandbox template.
# You can use template ID (jr829l6nnqz8gwyfpzbh) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("jr829l6nnqz8gwyfpzbh") # Sync sandbox
# sandbox = await AsyncSandbox.create("jr829l6nnqz8gwyfpzbh") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('jr829l6nnqz8gwyfpzbh')

team_id = "17f751d4-ae78-4116-97ca-8e445b02e44a"
memory_mb = 4_096
cpu_count = 2
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "jr829l6nnqz8gwyfpzbh"
